spring.application.name=rate-cs-teaching-staff
server.tomcat.accesslog.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://dpg-d8oaj7n7f7vs73egit50-a.oregon-postgres.render.com/cs_staff
spring.datasource.username=cs_staff_user
spring.datasource.password=oVnRYq710DinKf9mgzISiyaraMVgv2Nz
spring.session.jdbc.initialize-schema=always